# Generated by Django 2.0.7 on 2018-09-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChillerPlant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('indoor_temperature', models.FloatField()),
                ('outdoor_temperature', models.FloatField()),
                ('plant_name', models.CharField(max_length=15)),
                ('return_temperature', models.FloatField()),
                ('supply_temperature', models.FloatField()),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
    ]
